
const formConfig =  {
    "type":"container",
    "direction":"column",
    "children":[
        {
            type:"input",
            name:"name",
            label:"字段名",
            formItemProps:{
                
            },
            placeholder:"提交的字段名称",
        },
        {
            type:"input",
            name:"label",
            label:"表单名",
            formItemProps:{
                initialValue:"测试"
            },
            placeholder:"表单描述的文字",
        },
        {
            type:"inputNumber",
            name:"width",
            label:"宽度",
            formItemProps:{
                
            },
            placeholder:"默认不填为栅格宽度",
        },
        {
            type:"radioGroup",
            name:"mode",
            label:"类型",
            formItemProps:{
                initialValue:'default'
            },
            options:[{
                label:"默认",
                value:'default'
            },{
                label:"多选",
                value:"multiple"
            },{
                label:"标签",
                value:"tags"
            }]
        },
        {
            type:"switch",
            name:"allowClear",
            label:"允许清除",
            formItemProps:{
                valuePropName:"checked"
            },
        },
        {
            type:"switch",
            name:"showSearch",
            label:"允许搜索",
            formItemProps:{
                valuePropName:"checked",
                initialValue:false
            },
        },
        {
            type:"optionConfig",
            name:"options",
            label:"选项",
            formItemProps:{
                
            },
        }
    ]
}
module.exports = {formConfig}