
const formConfig =  {
    "type":"container",
    "direction":"column",
    "children":[
        {
            type:"input",
            formItemProps:{
                name:"name",
                label:"字段名",
            },
            props:{
                placeholder:"提交的字段名称",
            }
        },
        {
            type:"input",
            formItemProps:{
                name:"label",
                label:"表单名",
                initialValue:"测试"
            },
            props:{
                placeholder:"表单描述的文字",
            }
        },
        {
            type:"inputNumber",
            formItemProps:{
                name:"width",
                label:"宽度",
            },
            props:{
                placeholder:"默认不填为栅格宽度",
            }
        },
        {
            type:"radioGroup",
            formItemProps:{
                name:"mode",
                label:"类型",
                initialValue:'default'
            },
            props:{
                options:[{
                    label:"默认",
                    value:'default'
                },{
                    label:"多选",
                    value:"multiple"
                },{
                    label:"标签",
                    value:"tags"
                }]
            }
        },
        {
            type:"switch",
            formItemProps:{
                name:"allowClear",
                label:"允许清除",
                valuePropName:"checked"
            },
            props:{

            }
        },
        {
            type:"switch",
            formItemProps:{
                name:"showSearch",
                label:"允许搜索",
                valuePropName:"checked",
                initialValue:false
            },
            props:{

            }
        },
        {
            type:"optionConfig",
            formItemProps:{
                name:"options",
                label:"选项",
            },
            props:{
                
            }
        }
    ]
}
module.exports = {formConfig}